# Generated by Django 5.0.1 on 2024-05-13 19:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0002_bannerimage_alter_comments_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('announce', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 5, 14, 2, 48, 39, 227107))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 2, 48, 39, 227107)),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 5, 14, 2, 48, 39, 227107))),
                ('livestream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admissions.livestream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
