# Generated by Django 5.0.1 on 2024-05-13 20:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0005_faculty_alter_comments_time_alter_livestream_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 15, 48, 102977)),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 15, 48, 102977)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 15, 48, 102977)),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('mark', models.FloatField()),
                ('major', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='majorfk', to='Admissions.major')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('majors', models.ManyToManyField(blank=True, through='Admissions.Mark', to='Admissions.major')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='year',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='yearfk', to='Admissions.year'),
        ),
        migrations.AddField(
            model_name='major',
            name='years',
            field=models.ManyToManyField(blank=True, through='Admissions.Mark', to='Admissions.year'),
        ),
    ]
