# Generated by Django 5.0.1 on 2024-05-13 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0007_user_isadviser_user_iscandidate_alter_comments_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 32, 33, 618502)),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 32, 33, 618502)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 32, 33, 618502)),
        ),
    ]
